name: secondbrain
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_riverpod: ^3.1.0
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  path_provider: ^2.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.30.0
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
  generate: true
